# Generated by Django 4.1 on 2023-11-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arte',
            options={'ordering': ['id'], 'verbose_name': 'arte', 'verbose_name_plural': 'artes'},
        ),
    ]
